# Site settings
name: G2K Teachers' Schedule
description: G2K Teachers' schedule with photo gallery.

baseurl: "/photo-schedule" # the subpath of your site, e.g. /blog/
url: "https://tech-g2k.github.io" # the base hostname & protocol for your site

collections:
  photo_gallery:
